MesDepenses/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Http.OData;
using MesDepensesServices.DAL;
using MesDepensesServices.Domain;
using MesDepensesServices.Services;
using Repository.Pattern.UnitOfWork;

namespace MesDepenses.Controllers
{
    public class CategorieController : ApiController
    {
        private readonly CategorieService _categorieService;
        private readonly IUnitOfWorkAsync _unitOfWork;

        public CategorieController(CategorieService categorieService, IUnitOfWorkAsync unitOfWork)
        {
            _categorieService = categorieService;
            _unitOfWork = unitOfWork;
        }

        [EnableQuery,HttpGet]
        public IQueryable<Categorie> Get()
        {
            return _categorieService.Queryable();
        }

        // GET api/<controller>/5
        [ResponseType(typeof(Categorie)),HttpGet]
        public async Task<IHttpActionResult> Get(int id)
        {
            var categorie = await _categorieService.Queryable().FirstOrDefaultAsync(x => x.Id == id);
            if (categorie == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return Ok(_categorieService.Queryable().FirstOrDefault(x => x.Id == id));
        }

        [HttpPost]
        public async Task<IHttpActionResult> Post([FromBody]Categorie categorie)
        {
            _categorieService.Insert(categorie);
            if (await _unitOfWork.SaveChangesAsync() > 0)
                return Created(Request.RequestUri + categorie.Id.ToString(), categorie);
            return InternalServerError();
        }

        [HttpPut]
        public async Task<IHttpActionResult> Put(int id, [FromBody]Categorie cat)
        {
            var categorie = await _categorieService.Queryable().FirstOrDefaultAsync(x => x.Id == id);
            if (categorie == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            categorie.Libelle = cat.Libelle;
            categorie.CategorieParent = cat.CategorieParent;
            await _unitOfWork.SaveChangesAsync();
            return Ok();
        }

        [HttpDelete]
        public async Task<IHttpActionResult> Delete(int id)
        {
            if (_categorieService.Queryable().Any(x => x.Id == id))
            {
                await _categorieService.DeleteAsync(id);
                if (await _unitOfWork.SaveChangesAsync() > 0)
                    return Ok();
                return InternalServerError();
            }
            return NotFound();
        }
    }
}

MesDepenses/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Web;
using System.Web.Mvc;
using log4net;
using MesDepenses.Models;
using MesDepensesServices;
using MesDepensesServices.DAL;
using MesDepensesServices.Domain;
using ToolsLibrary;

namespace MesDepenses.Controllers
{
  public class HomeController : Controller
  {
    private static readonly ILog _log = LogManager.GetLogger("MesDepenses");

    public ActionResult Index()
    {
      _log.Error("test error");
      var compte = new CompteModel();
      DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(List<OperationModel>));
      var stream = new StreamReader(Server.MapPath("~/App_Data/CyberPlus_OP_1_20141001165451.csv"), Encoding.Default);
      MemoryStream s = new MemoryStream(Encoding.UTF8.GetBytes(stream.ReadToEnd().CsvToJson()));
      compte.ListOperation = (List<OperationModel>)ser.ReadObject(s);

      return View();
    }

    public ActionResult TestTools()
    {
      var compte = new CompteModel();
      DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(List<OperationModel>));
      var stream = new StreamReader(Server.MapPath("~/App_Data/CyberPlus_OP_1_20141001165451.csv"), Encoding.Default);
      MemoryStream s = new MemoryStream(Encoding.UTF8.GetBytes(stream.ReadToEnd().CsvToJson()));
      compte.ListOperation = (List<OperationModel>)ser.ReadObject(s);
      compte.ListOperation.ForEach(x => x.History = new History { CreationDate = DateTime.Now, IsNew = true, OperationName = x.Libelle });
      //compte.ListOperation.OrderBy("Libelle", EnumerableExtensions.SortDirection.asc);
      compte.ListOperation.OrderBy("History.CreationDate", EnumerableExtensions.SortDirection.asc);
      return View(compte.ListOperation);
    }

    public ActionResult About()
    {
      ViewBag.Message = "Your app description page.";
      return View();
    }

    public ActionResult Contact()
    {
      ViewBag.Message = "Your contact page.";
      return View();
    }

    public PartialViewResult MyOperations()
    {
      return PartialView();
    }

    public PartialViewResult MyCategories()
    {
      return PartialView();
    }

    public JsonResult ReadData()
    {
      var stream = new StreamReader(Server.MapPath("~/App_Data/CyberPlus_OP_1_20141001165451.csv"), Encoding.Default);
      //TODO: async 
      var tmp = stream.ReadToEnd().CsvToJson();
      return Json(tmp, JsonRequestBehavior.AllowGet);
    }
  }
}

MesDepenses/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

MesDepenses/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

MesDepenses/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

 

MesDepenses/Views/Home/MyCategories.cshtml
<div class="row">
    <div id="breadcrumb" class="col-md-12">
        <ol class="breadcrumb">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Tables</a></li>
            <li><a href="#">Data Tables</a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-usd"></i>
                    <span>Mes Catégroies</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding" id="table">
                <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-3">
                    <thead>
                        <tr>
                            <th>Id
                            </th>
                            <th>Libellé
                            </th>
                            <th>Categorie Parente
                            </th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: items">
                        <tr data-toggle="tooltip" data-bind="tooltip: { title: Libelle, trigger: 'hover', placement: 'bottom' }" data-container="body">
                            <td><span data-bind="text: Id"></span>
                                <input type="checkbox" data-bind="value: $data, checked: $parent.selectedItems, attr: { id: 'checkBox' + Id }" /></td>
                            <td data-bind="text: Libelle"></td>
                            <td data-bind="text: CategorieParent"></td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Libellé
                            </th>
                            <th>Date
                            </th>
                            <th>Montant
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-8">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-search"></i>
                    <span>Nouvelle catégorie</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content">
                <form id="defaultForm" method="post" action="@Url.Action("Post", "Categorie", new { httproute = "" })" class="form-horizontal">
                    <fieldset>
                        @*<legend>Not Empty validator</legend>*@
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Libellé</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" name="Libelle" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Catégorie parente</label>
                            <div class="col-sm-5">
                                <select class="populate placeholder" name="CategorieParent" id="CategorieParent" data-bind="options: items, optionsText: function (item) { return item.Libelle; }, value: function (item) { return item.Id; }, optionsCaption: 'Choose...'">
                                </select>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <div class="col-sm-9 col-sm-offset-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<div data-bind="text: ko.toJSON($root)"></div>
<script type="text/javascript">

    var CategorieVM = function (id, libelle, categorieParent) {
        var self = this;
        this.Id = ko.observable(id);
        this.Libelle = ko.observable(libelle);
        this.CategorieParent = ko.observable(categorieParent);
        this.$type = 'CategorieVM';
    };
    var urlGetData = '@Url.Action("Get", "Categorie", new { httproute = "" })';
    var urlDeleteData = '@Url.RouteUrl("DefaultApi", new { httproute = "", controller = "Categorie", id = "00000" })';
    var ViewModel = function () {
        var self = this;

        self.items = ko.observableArray();
        self.selectedItems = ko.observableArray();

        self.removeItem = function (item) {
            self.items.remove(item);
        };
        
        self.removeSelected = function () {
            BootstrapDialog.show({
                title: 'Suppression de Catégorie',
                message: 'Are youe sûr',
                buttons: [{
                    label: 'Annuler',
                    action: function (dialog) {
                        dialog.close();
                    }
                }, {
                    label: 'Delete',
                    action: function (dialog) {
                        ko.utils.arrayForEach(self.selectedItems(), function (item) {
                            $.ajax({
                                url: urlDeleteData.replace('00000', item.Id()),
                                type: 'DELETE',
                                dataType: 'json',
                                crossDomain: true,
                                headers: { "Accept": "application/json", "Content-Type": "application/json" },
                                success: function (data, textStatus, xhr) {
                                    console.log(data);
                                },
                                error: function (xhr, textStatus, errorThrown) {
                                    console.log('Error in Operation : ' + errorThrown);
                                }
                            });
                        });
                        self.items.removeAll(self.selectedItems());
                        self.selectedItems.removeAll();
                        dialog.close();
                    }
                }]
            });
        };

        self.load = function () {
            $.getJSON(urlGetData, function (data) {
                //console.log(JSON.parse(data));
                var mappedData = ko.utils.arrayMap(data, function (item) {
                    return new CategorieVM(item.Id, item.Libelle, item.CategorieParent);
                });
                self.items(mappedData);

            });
        };

        self.load();
    };
    $.fn.serializeForm = function () {
        return _.object(_.map($(this).serializeArray(), function (item) { return [item.name, item.value]; }));
    };

    var catModel = new ViewModel();

    $(function () {

        ko.cleanNode($("#ajax-content")[0]);

        ko.applyBindings(catModel, $("#ajax-content")[0]);
        $("[data-toggle='tooltip']").tooltip();
        // Run Datables plugin and create 3 variants of settings
        function AllTables() {
            TestTable3();
            LoadSelect2Script(MakeSelect2);
        }

        function MakeSelect2() {
            $('select').select2();
            $('.dataTables_filter').each(function () {
                $(this).find('label input[type=text]').attr('placeholder', 'Search');
            });
        }

        // Load Datatables and run plugin on tables 
        LoadDataTablesScripts(AllTables);

        // Add Drag-n-Drop feature
        WinMove();
        $("form").on("submit", function (event) {

            event.preventDefault();
            $.ajax({
                url: $(this).attr('action'),
                data: JSON.stringify($(this).serializeForm()),
                type: "POST",
                contentType: "application/json;charset=utf-8",
                statusCode: {
                    201: function (newcat) {
                        // console.dir(newcat);
                    }
                }
            });
        });

    });
</script>

MesDepenses/Views/Home/MyOperations.cshtml
@*<div class="actions">
    <input type="button" value="group by" data-bind="click: groupBy" />
    <input type="button" value="sort by" data-bind="click: sortBy" />
</div>*@

<div class="row">
    <div id="breadcrumb" class="col-md-12">
        <ol class="breadcrumb">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Tables</a></li>
            <li><a href="#">Data Tables</a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-usd"></i>
                    <span>Mes Operations</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="expand-link">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding" id="table">
                <table class="table table-bordered table-striped table-hover table-heading table-datatable" id="datatable-3">
                    <thead>
                        <tr>
                            <th>Libellé
                            </th>
                            <th>Date
                            </th>
                            <th>Montant
                            </th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: items">
                        <tr data-toggle="tooltip" data-bind="tooltip: { title: Libelle, trigger: 'hover', placement: 'bottom' }" data-container="body">
                            <td data-bind="text: SimpleLibelle"></td>
                            <td data-bind="text: Datevaleur"></td>
                            <td data-bind="text: Montant"></td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Libellé
                            </th>
                            <th>Date
                            </th>
                            <th>Montant
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    //var carteregex = "^carte[ ]+([0-9]{6})+[ ]+cb:\\*([0-9]{7})[ ]+([a-z-A-Z.]+)+[ ]+([0-9]{2})(.+)$";
    var carteregex = "^carte[ ]+([0-9]{6})+[ ]+cb:\\*([0-9]{7})[ ]+(.+)$";

    var OperationVM = function (montant, libelle, datevaleur, reference, compte) {
        var self = this;
        this.Montant = ko.observable(montant);
        this.Libelle = ko.observable(libelle);
        this.Datevaleur = ko.observable(datevaleur);
        this.Reference = ko.observable(reference);
        this.Compte = ko.observable(compte);
        this.isCarte = ko.observable(false);
        this.isPrlv = ko.observable(false);
        this.isRetrait = ko.observable(false);
        this.isCheque = ko.observable(false);
        this.$type = 'OperationVM';
        this.SimpleLibelle = ko.dependentObservable(function () {
            var myRegexp = new RegExp(carteregex, "gi");
            //console.log(self.Libelle());

            var match = myRegexp.exec(self.Libelle());
            if (match != null) {
                self.isCarte = true;
                return match[3];
            }
            return self.Libelle();
        }, this);


    };

    var urlGetData = '@Url.Action("ReadData", "Home")';
    var ViewModel = function () {
        var self = this;

        self.items = ko.observableArray();

        self.compteLength = ko.computed(function () {
            return self.items().length;
        }, this);

        self.groupBy = function () {
            var tmp = _.groupBy(self.items(), function (item) {
                return item.Montant().length;
            });
            self.items(tmp);
        };

        self.sortBy = function () {
            self.items(_.sortBy(self.items(), function (item) { return parseInt(item.Montant()); }));
        };

        self.load = function () {
            $.getJSON(urlGetData, function (data) {
                //console.log(JSON.parse(data));
                var mappedData = ko.utils.arrayMap(JSON.parse(data), function (item) {
                    return new OperationVM(item.Montant, item.Libelle, item.Datevaleur, item.Reference, item.Compte);
                });
                self.items(mappedData);

            });
        };
        self.load();
    };
    $(function () {
        ko.cleanNode($("#ajax-content")[0]);
        ko.applyBindings(new ViewModel(), $("#ajax-content")[0]);
        $("[data-toggle='tooltip']").tooltip();
        // Run Datables plugin and create 3 variants of settings
        function AllTables() {
            TestTable3();
            LoadSelect2Script(MakeSelect2);
        }
        function MakeSelect2() {
            $('select').select2();
            $('.dataTables_filter').each(function () {
                $(this).find('label input[type=text]').attr('placeholder', 'Search');
            });
        }

        // Load Datatables and run plugin on tables 
        LoadDataTablesScripts(AllTables);
        // Add Drag-n-Drop feature
        WinMove();

    });
</script>

MesDepenses/Views/Home/TestTools.cshtml
@model List<MesDepenses.Models.OperationModel>

<div class="row">
    <table>
        <thead>
            <tr>
                <td>Libelle</td>
                <td>Operation Name</td>
                <td>IsNew</td>
                <td>CreationDate</td>
                <td>Montant</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var op in Model)
            {
                <tr>
                    <td>@op.Libelle</td>
                    <td>@op.History.OperationName</td>
                    <td>@op.History.IsNew</td>
                    <td>@op.History.CreationDate</td>
                    <td>@op.Montant</td>
                </tr>
            }
        </tbody>
    </table>
</div>